[tools]
# https://mise-tools.jdx.dev/tools/bun
bun = "1.3.2"
# https://mise-tools.jdx.dev/tools/biome
biome = "2.3.15"
# https://mise-tools.jdx.dev/tools/lefthook
lefthook = "latest"
# https://mise-tools.jdx.dev/tools/golangci-lint
golangci-lint = "latest"
